/*
`7MMM.     ,MMF'      db      `7MM"""Yb.   
  MMMb    dPMM       ;MM:       MM    `Yb. 
  M YM   ,M MM      ,V^MM.      MM     `Mb 
  M  Mb  M' MM     ,M  `MM      MM      MM 
  M  YM.P'  MM     AbmmmqMA     MM     ,MP 
  M  `YM'   MM    A'     VML    MM    ,dP' 
.JML. `'  .JMML..AMA.   .AMMA..JMMmmmdP'   
         ( MAD Services © جميع الحقوق محفوظه لدى )
            - 🌹 لك كامل صلاحية التعديل 🌹
*/
// Language configuration for the ticket system
exports.language = {
    default: 'ar', // Default language
    
    // Messages for Arabic
    ar: {
        no_access: '❌ | **لاتمتلك صلاحية لـ إستخدام الأمر ..**',
        rate_title: '💛 | {target} (تقييمك يُهمنا ويصنع الفرق)',
        rate_requested: '**تم طلب تقييم بـ نجاح ..**',
        incorrect_ticket: '**لم يتم التعرف على التذكرة في النظام**',
        added_toticket: '**تم إضافة {target} بـ نجاح إلى التذكرة**',
        removed_frticket: '**تم إزالة {target} بـ نجاح من التذكرة**',
        click_to: `إضغط هُنا لفتح تذكرة بـ هذا التصنيف`,
        no_db: `**هذا الشخص لايمتلك داتا بيس في قاعدة البيانات ..**`,
        requestbill: {
            emoji: `💵`,
            label: `طلب الفاتورة`,
            description: `Total price: {total}$`,
            incart1: `Price: {price}$ (بالعربة)`,
            emoji1: `❌`,
            incart2: `Price: {price}$`,
            emoji2: `🛍️`,
            total: `{title} إجمالي المبلغ : {total} دولار`,
            select: `إختر مُنتجاتك , بعد الإختيار أضغط على " طلب الفاتورة "`,
            no_product: `لايوجد طلب & طلب خاص`,
            new_order: `تعديل الطلب`,
            new_order_desc: `إضغط هُنا لتعديل طلبك الحالي .`,
            bill: `إجمالي المبلغ المُستحق : {total}$`,
            no_item: `لم تقم بإضافة أي مُنتج , أشرح طلبك الخاص وسيتم الرد عليك من قبل المسؤولين .`,
        },
        blacklisted: `**أنت في القائمة السوداء لاتستطيع فتح تذكرة ..**`,
        must_have: `**أنت لاتمتلك رتبة {role} لـ فتح هذه التصنيف من التذاكر ..**`,
        antispam: '**يجب عليك الإنتظار كحد أقصى 5 ثواني بين كل إستخدام للأزرار ..**',
        only_creator: '**فقط صانع التذكرة يستطيع التقييم ..**',
        staff_menus: [
            { emoji: `📜`, label: `إرسال رسالة خاصة`, description: `إلى صاحب التذكرة`, value: `StaffX_Options1` },
            { emoji: `🔔`, label: `إرسال تنبية بالخاص`, description: `إلى صاحب التذكرة`, value: `StaffX_Options2` },
            { emoji: `👾`, label: `طلب تقييم من الشخص`, description: `من صاحب التذكرة`, value: `StaffX_Options_rateX` },
            { emoji: `🔐`, label: `إغلاق التذكرة`, description: `لن يتم حذفها فقط إخفائها`, value: `StaffX_Options3` },
            { emoji: `⛔`, label: `حذف التذكرة`, description: `سيتم حذف الروم وإرسال جميع المعلومات في اللوق`, value: `StaffX_Options4` },
            { emoji: `📍`, label: `تثبيت التذكرة`, description: `عند تثبيتها سيتم إلغاء الحذف التلقائي`, value: `StaffX_Pin` },
        ],
        staff_select: `إضغط هُنا لـ عرض الإجرائات المُتاحة لك كمسؤول .`,
        requested_by: `تم طلبها بواسطتك ;)`,
        creator_select: `قم بإختيار الزر المُناسب لك .`,
        save: `حفظ`,
        delete: `حذف`,
        close: `اغلاق`,
        already_closed: '**التذكرة مُغلقة بالفعل من قبل !**',
        user_options: `خيارات العضو`,
        staff_options: `خيارات المسؤول`,
        chys: `**لاتستطيع إستلام تذكرتك !**`,
        claim: `إستلام التذكرة`,
        reminder: `نرجو منك مُراجعة التذكرة الخاصه بك ,, إهمالها يؤدي إلى حذفها ..`,
        reminder_sent: '✅ **تم إرسال تنبيه لـ مراجعة التذكرة إلى ({target})**',
        responsible: '**مسؤول التذكرة هو : {responsible}**',
        blacklist1: 'غير محظور ❌',
        blacklist2: 'محظور ✅',
        already_hasTicket: 'يوجد لديك تذكرة فعالة : {tickets} ({num})',
        managers_online: 'المسؤولين المُتصلين',
        ticket_num: 'رقم التذكرة',
        paypal: {
            invoiceurl: 'رابط الفاتورة',
            confirm: 'تأكيد الدفع',
            cancel: 'إلغاء الفاتورة',
            payfirst: '**يجب أن تقوم بدفع الفاتورة اولاً ثم أكد التحويل**!',
            totalpaid: 'إجمالي المبلغ المدفوع : {total}$'
        },
        ticket_created: '✅ تم إنشاء تذكرتك في {channel}',
        ticket_closed: '🔒 تم إغلاق التذكرة بواسطة {user}',
        ticket_claimed: '✅ تم استلام التذكرة بواسطة {user}',
        ticket_reopened: '🔓 تم إعادة فتح التذكرة بواسطة {user}',
        no_permission: '❌ ليس لديك صلاحية لهذا الإجراء',
        max_tickets: '❌ لديك الحد الأقصى من التذاكر المفتوحة',
        payment_success: '💰 تم استلام الدفعة بنجاح!',
        payment_failed: '❌ فشلت عملية الدفع: {reason}',
        invoice_created: '📋 تم إنشاء الفاتورة: {amount} {currency}',
    },

    // Messages for English
    en: {
        no_access: '❌ | **You don\'t have access to use this cmd ..**',
        rate_title: '💛 | {target} (Your rating matters to us)',
        rate_requested: '✅ | **Rate was requested**',
        incorrect_ticket: '**Can\'t find this ticket in our system.**',
        added_toticket: '✅ | **{target} Was successfully added to the ticket.**',
        removed_frticket: '✅ | **{target} Was successfully removed from the ticket.**',
        click_to: `Click here to open a ticket in this category`,
        no_db: `❌ | **This user don't have a database in the system**`,
        requestbill: {
            emoji: `💵`,
            label: `Request the bill`,
            description: `Total price: {total}$`,
            incart1: `Price: {price}$ (In cart)`,
            emoji1: `❌`,
            incart2: `Price: {price}$`,
            emoji2: `🛍️`,
            total: `{title} Total amount: {total}$`,
            select: `Select your products , then click on " request the bill "`,
            no_product: `No products & Special order`,
            new_order: `Edit the order`,
            new_order_desc: `Click here to edit your current order`,
            bill: `Total due: {total}$`,
            no_item: `You have'nt add any product, explain your special order and the administrators will respond to you ASAP.`,
        },
        blacklisted: `❌ | **You're Blacklisted ;)**`,
        must_have: `❌ | **You don't have {role} to open this ticket**`,
        antispam: '❌ | **You have to wait at least 5sec before doing anything again.**',
        only_creator: '❌ | **Only the ticket creator can rate!**',
        staff_menus: [
            { emoji: `📜`, label: `Send special message`, description: `To the ticket creator`, value: `StaffX_Options1` },
            { emoji: `🔔`, label: `Send quick notify`, description: `To the ticket creator`, value: `StaffX_Options2` },
            { emoji: `👾`, label: `Request rate`, description: `From ticket creator`, value: `StaffX_Options_rateX` },
            { emoji: `🔐`, label: `Close the ticket`, description: `Channel will be closed & moved to closed category`, value: `StaffX_Options3` },
            { emoji: `⛔`, label: `Delete the ticket`, description: `Channel will be removed and send the copy in the logs`, value: `StaffX_Options4` },
            { emoji: `📍`, label: `Pin the ticket`, description: `When pin the ticket will stop the auto delete`, value: `StaffX_Pin` },
        ],
        staff_select: `Click here to view the actions available to you as an administrator.`,
        requested_by: `Requested by you ;)`,
        creator_select: `Choose the button that you want.`,
        save: `Save`,
        delete: `Delete`,
        close: `Close`,
        already_closed: '**Ticket already closed!**',
        user_options: `User options`,
        staff_options: `Manager options`,
        chys: `**You can't claim your ticket ;)**`,
        claim: `Claim the ticket`,
        reminder: `Check your ticket please, otherwise will be deleted.`,
        reminder_sent: '✅ **Message was sent to ({target})**',
        responsible: '**Ticket responsible : {responsible}**',
        blacklist1: 'Not BlackListed❌',
        blacklist2: 'BlackListed ✅',
        already_hasTicket: 'Already have active ticket: {tickets} ({num})',
        managers_online: 'Managers Online',
        ticket_num: 'Ticket Num.',
        paypal: {
            invoiceurl: 'Invoice url',
            confirm: 'Confirm',
            cancel: 'Cancel',
            payfirst: '**You have to pay the invoice then confirm the transaction**!',
            totalpaid: 'Total amount paid: {total}$'
        },
        ticket_created: '✅ Your ticket has been created in {channel}',
        ticket_closed: '🔒 Ticket closed by {user}',
        ticket_claimed: '✅ Ticket claimed by {user}',
        ticket_reopened: '🔓 Ticket reopened by {user}',
        no_permission: '❌ You don\'t have permission for this action',
        max_tickets: '❌ You have reached the maximum number of open tickets',
        payment_success: '💰 Payment received successfully!',
        payment_failed: '❌ Payment failed: {reason}',
        invoice_created: '📋 Invoice created: {amount} {currency}',
    }
};
